### PR TITLE
demo app sample

### PR DESCRIPTION
**Pull request by sfc-gh-eraigosa**

### CODE REVIEW

**Comment by Carlosgsuarez** [comment]
Thank you Edward, a question: Is this a section of the repo  to test azure configuration or what is it?

**Comment by sfc-gh-eraigosa** [comment]
> Thank you Edward, a question: Is this a section of the repo to test azure configuration or what is it?

Yes, I was testing getting a very simple demo app deployed to make sure like networking is working as expected. This weekend I was able to get a k8s cluster finally authenticating and connecting properly with ingress the way I was expecting, which means if I get this demo app working we'll be able to attempt the same with some of our own components.

**Comment by Carlosgsuarez** [comment]
Ok great, keep us posted

**Comment by sfc-gh-eraigosa** [comment]
I'm now troubleshooting this error

```
W0411 19:18:35.599448       7 controller.go:977] Service "human-connection/neo4j" does not have any active Endpoint.
```

This is a problem with the ingress service not discovering the app service.

**Comment by sfc-gh-eraigosa** [comment]
Ok, this issue is solved now and we have an API service here http://redsol.eastus.cloudapp.azure.com/

It's good for development so we'll need to do some more testing to make sure it's working but they'll be more task to improve this for production. Those would be things like;

- some test for the endpoints
- backups
- security, secrets in AKV
- end point protection (ssl, creds ??)
- ci/cd

There might be more as we progress but that's a good setup we have now. Currently this will cost 50-60 /month, so we can probably have a second env for production once we get there.

**Pull request merged**
